### ISSUE TITLE
App can't find the folder I set in the config

### ISSUE THREAD

**Issue by ItsNiceCraft** [deusprogrammer/wtd-tool-electron#1]
The app neither shows already existing clips nor saves new clips, error in DevTools:

`asyncToGenerator.js:6 Uncaught (in promise) Error: Error invoking remote method 'getVideos': Error: ENOENT: no such file or directory, <scandir path to the game, censored>`

**Comment by deusprogrammer** [comment]
Try selecting the directory that contains the “StreamingAssets” folder for now.  It just now occurred to me that it probably wasn’t the most logical directory to make you select.  Next version I will just have you select the base directory for it.  Give that a try and let me know if it works.

**Comment by deusprogrammer** [comment]
And thank you for reporting the bug =).
